modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Vazkii/Patchouli"
logoFile="logo.png"

[[mods]]
modId="patchouli"
displayName="Patchouli"
version="${version}"
authors="Vazkii"
description='''
Accessible, Data-Driven, Dependency-Free Documentation for Minecraft Modders and Pack Makers
'''

[[dependencies.patchouli]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.75,)"
