name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
    - name: Build with Gradle
      run: ./gradlew pmdMain spotlessJavaCheck build
    - name: Run GameTests (Fabric)
      run: ./gradlew :Fabric:runGameTest
