name: Test docs

on:
  pull_request:
    paths:
      - 'web/**'

jobs:
  test-docs:
    name: Test docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: 'web/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./web
      - name: Build website
        run: yarn build
        working-directory: ./web